### ISSUE TITLE
Stat

### ISSUE THREAD

**Issue by G2cme** [github/scientist#252]
[![Coverage Status](https://coveralls.io/builds/33262793/badge)](https://coveralls.io/builds/33262793)

Coverage increased (+0.03%) to 99.119% when pulling **66823c9d693b6a5fa88a36907b27f9502ccad21f on rlue:api/register_method** into **25a22f733d4be523404b22ad818e520d20b57619 on github:master**.

_Originally posted by @coveralls in https://github.com/github/scientist/issues/104#issuecomment-505710533_
            
```[tasklist]
### Tasks
- [ ] https://github.com/github/scientist/issues/251
- [ ] https://github.com/github/scientist/issues/162
- [ ] https://github.com/github/scientist/pull/104
- [ ] https://github.com/github/scientist/issues/243
```

```[tasklist]
### Tasks
- [ ] https://github.com/github/scientist/issues/162
```
